### ISSUE TITLE
pdoc --html flag not available.

### ISSUE THREAD

**Issue by chriz-uniba** [Materials-Data-Science-and-Informatics/iridium#7]
Maybe my setup is outdated but for me this command doesn't run through:

# Error

https://github.com/Materials-Data-Science-and-Informatics/iridium/blob/4d357dc9d61aebfedd3c3e6a6b6451798c2c7122/README.md?plain=1#L92

```
$ pdoc --html -o docs iridium
usage: pdoc [-o DIR] [-d {google,numpy,restructuredtext}] [-e module=url] [--footer-text TEXT] [--logo URL] [--logo-link URL] [--math | --no-math] [--search | --no-search] [--show-source | --no-show-source] [-t DIR] [-h HOST] [-p PORT] [-n] [--help] [--version] [module ...]
pdoc: error: unrecognized arguments: --html
```

# Setup
```
$ pdoc --version
pdoc: 8.3.0
Python: 3.9.2
Platform: Linux-5.10.0-11-amd64-x86_64-with-glibc2.31
```
# Working command

```
$ pdoc -o docs iridium
```

Creates

```
.
├── index.html
├── iridium
│   ├── api.html
│   ├── generic.html
│   ├── inveniordm
│   │   ├── models
│   │   │   ├── base.html
│   │   │   ├── biblio.html
│   │   │   ├── query.html
│   │   │   └── technical.html
│   │   └── models.html
│   ├── inveniordm.html
│   ├── pprint.html
│   ├── query.html
│   ├── record.html
│   └── util.html
├── iridium.html
└── search.js

3 directories, 15 files
```

Do we need to fix the Readme, or do I need to fix my setup? If it is my setup, let me know what is needed (and maybe add this to the Readme, too). ;)

**Comment by mhils** [comment]
pdoc works as you describe, only pdoc3 would require you to pass `--html`. Both are different projects (https://github.com/mitmproxy/pdoc#pdoc-vs-pdoc3). 

Given that `pyproject.toml` states `pdoc`, I think you can adjust the Readme. :-)
